import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   Excellent. We now have enough information to move forward. The frontend is in a good state.
   
   MEMsAI Frontend Audit Result
   
   Current files:
   
   frontend/
   └── app/
       ├── favicon.ico
           ├── globals.css
               ├── layout.tsx
                   └── page.tsx
                   
                   This is the clean default Next.js 16 App Router structure.
                   
                   ⸻
                   
                   What is already correct ✅
                   
                   page.tsx
                   
                   Your landing page has already been replaced with the MEMsAI concept.
                   
                   Current state:
                   
                   ✅ Branding:
                   
                   MEMsAI
                   
                   ✅ Message:
                   
                   Your Intelligence. Your Memory. Your Control.
                   
                   ✅ Product positioning:
                   
                   A secure, user-owned memory vault...
                   
                   This is exactly the right direction for the MVP.
                   
                   ⸻
                   
                   What needs improvement before continuing
                   
                   1. Update metadata
                   
                   Currently:
                   
                   title: "Create Next App"
                   description: "Generated by create next app"
                   
                   This is still the starter template identity.
                   
                   We should change it to MEMsAI.
                   
                   ⸻
                   
                   Open:
                   
                   nano app/layout.tsx
                   
                   (or edit in Codespaces)
                   
                   Change:
                   
                   export const metadata: Metadata = {
                     title: "Create Next App",
                       description: "Generated by create next app",
                       };
                       
                       to:
                       
                       export const metadata: Metadata = {
                         title: "MEMsAI | Your Intelligence. Your Memory. Your Control.",
                           description:
                               "MEMsAI is a secure, user-owned memory platform that allows people to control, protect, and share their personal intelligence with AI assistants.",
                               };
                               
                               ⸻
                               
                               2. Improve the layout foundation
                               
                               Your current:
                               
                               <body className="min-h-full flex flex-col">
                               
                               is okay, but for a platform we should prepare the global shell.
                               
                               Change it to:
                               
                               <body className="min-h-screen flex flex-col antialiased">
                               
                               This aligns better with Tailwind 4 + modern React rendering.
                               
                               ⸻
                               
                               3. Keep Geist fonts
                               
                               Do not remove:
                               
                               import { Geist, Geist_Mono } from "next/font/google";
                               
                               Good choice.
                               
                               MEMsAI is positioned as a modern AI infrastructure platform, and Geist fits that aesthetic.
                               
                               ⸻
                               
                               Next milestone: Create the MEMsAI Design System
                               
                               Before creating dashboard pages, we should establish reusable components.
                               
                               We will add:
                               
                               frontend/
                               components/
                               ├── ui/
                               │   ├── Button.tsx
                               │   ├── Card.tsx
                               │   └── Container.tsx
                               │
                               ├── layout/
                               │   ├── Navbar.tsx
                               │   └── Footer.tsx
                               │
                               └── vault/
                                   └── MemoryCard.tsx
                                   lib/
                                   ├── utils.ts
                                   types/
                                   └── index.ts
                                   
                                   Why?
                                   
                                   Because MEMsAI will eventually have:
                                   
                                   * user vaults,
                                   * AI agents,
                                   * memory permissions,
                                   * enterprise dashboards.
                                   
                                   We don’t want hundreds of duplicated UI elements later.
                                   
                                   ⸻
                                   
                                   Before creating components, let’s commit this checkpoint
                                   
                                   Run:
                                   
                                   git status
                                   
                                   You should see:
                                   
                                   modified:
                                   app/page.tsx
                                   
                                   Then:
                                   
                                   git add .
                                   git commit -m "Create MEMsAI landing page foundation"
                                   git push
                                   
                                   ⸻
                                   
                                   After commit, Sprint 1.2
                                   
                                   We will create:
                                   
                                   MEMsAI Application Shell
                                   
                                   First components:
                                   
                                   Navbar
                                    |
                                     ├── Logo
                                      ├── Product
                                       ├── Security
                                        ├── Documentation
                                         └── Enter Vault
                                         Landing Page
                                         Footer
                                         
                                         Then:
                                         
                                         Sprint 2
                                         
                                         Connect:
                                         
                                         Next.js Frontend
                                                 |
                                                         |
                                                                 ↓
                                                                 FastAPI Backend
                                                                         |
                                                                                 |
                                                                                         ↓
                                                                                         PostgreSQL
                                                                                         
                                                                                         ⸻
                                                                                         
                                                                                         One more thing: I noticed from your earlier output that the backend has only:
                                                                                         
                                                                                         backend/app/main.py
                                                                                         
                                                                                         So after the frontend checkpoint, we should inspect main.py before designing the API connection. That will prevent us creating endpoints that conflict with your existing architecture.
                                                                                         
                                                                                         Your next action:
                                                                                         
                                                                                         1. Update layout.tsx metadata.
                                                                                         2. Commit.
                                                                                         3. Paste the output of:
                                                                                         
                                                                                         git status
                                                                                         
                                                                                         and after that we move into the MEMsAI UI foundation. <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
